修改引用模块

diff --git a/tests/_utils/run_services b/tests/_utils/run_services
--- a/tests/_utils/run_services
+++ b/tests/_utils/run_services
@@ -15,48 +15,39 @@
 
 set -eu
 
-export PD_PEER_ADDR="127.0.0.1:2380"
-export PD_ADDR="127.0.0.1:2379"
-export TIDB_IP="127.0.0.1"
-export TIDB_PORT="4000"
-export TIDB_ADDR="127.0.0.1:4000"
-export TIDB_STATUS_ADDR="127.0.0.1:10080"
-# actual tikv_addr are TIKV_ADDR${i}
-export TIKV_ADDR="127.0.0.1:2016"
-export TIKV_STATUS_ADDR="127.0.0.1:2018"
-export TIKV_COUNT=3
-export TIFLASH_STATUS="127.0.0.1:17000"
-export TIFLASH_HTTP="127.0.0.1:8125"
-export IMPORTER_ADDR="127.0.0.1:8808"
-export TIKV_PIDS="${TEST_DIR:?}/tikv_pids.txt"
+TEST_DIR=/tmp/backup_restore_test
+
+PD_ADDR="127.0.0.1:2379"
+TIDB_IP="127.0.0.1"
+TIDB_PORT="4000"
+TIDB_ADDR="127.0.0.1:4000"
+TIDB_STATUS_ADDR="127.0.0.1:10080"
+# actaul tikv_addr are TIKV_ADDR${i}
+TIKV_ADDR="127.0.0.1:2016"
+TIKV_STATUS_ADDR="127.0.0.1:2018"
+TIKV_COUNT=3
+TIFLASH_STATUS="127.0.0.1:17000"
+TIFLASH_HTTP="127.0.0.1:8125"
 
 cleanup_data() {
     # Clean up data
-    for svc in "br" "tidb" "tiflash" "tikv" "pd" "importer"; do
+    for svc in "br" "tidb" "tiflash" "tikv" "pd"; do
         find "$TEST_DIR" -maxdepth 1 -name "${svc}*" -type d -exec echo delete {} \; -exec rm -rf {} \; 2> /dev/null
     done
 }
 
-stop() {
-    svc=$1
-    killall -v -1 "$svc" 2>/dev/null || return 0
-    sleep 1 # give some grace shutdown period
-    killall -v -9 "$svc" &>/dev/null || return 0
-}
-
 stop_services() {
-    for svc in "br" "tidb-server" "tiflash" "TiFlashMain" "tikv-server" "pd-server" "cdc" "minio" "tikv-importer"; do
-        stop $svc &
+    for svc in "br" "tidb" "tiflash" "tikv" "pd" "TiFlashMain"; do
+        # tiflash and br do not have "-server"
+        killall -9 $svc-server &> /dev/null || true
+        killall -9 $svc &> /dev/null || true
     done
-    sleep 2 # give some time for the OS to reap all processes
-    lsof -n -P -i :2379 -i :4000 -i :10080 -i :20161 -i :20162 -i :20163 -i :20181 -i :20182 -i :20183 -i :17000 -i :8125 || true
 }
 
 start_services() {
     max_retry=3
     for retry_time in $(seq 1 $max_retry); do
-        # run it in a subshell so the failure won't stop execution.
-        if ( start_services_impl "$@" ); then
+        if start_services_impl $@; then
             return 0
         fi
         stop_services
@@ -67,18 +58,30 @@ start_services() {
     return 1
 }
 
-start_pd() {
+start_services_impl() {
+    stop_services
+    cleanup_data
+
+    source tests/_utils/make_tiflash_config
+
+    TIDB_CONFIG="${1-tests}/config/tidb.toml"
+    TIKV_CONFIG="${1-tests}/config/tikv.toml"
+    PD_CONFIG="${1-tests}/config/pd.toml"
+    TIFLASH_CONFIG="${1-tests}/config/tiflash.toml"
+
+    if [ ! -e $PD_CONFIG ]; then PD_CONFIG=tests/config/pd.toml; fi
+    if [ ! -e $TIFLASH_CONFIG ]; then TIFLASH_CONFIG=tests/config/tiflash.toml; fi
+
     echo "Starting PD..."
     mkdir -p "$TEST_DIR/pd"
     bin/pd-server \
-        --client-urls "https://$PD_ADDR" \
-        --peer-urls "https://$PD_PEER_ADDR" \
+        --client-urls "http://$PD_ADDR" \
         --log-file "$TEST_DIR/pd.log" \
         --data-dir "$TEST_DIR/pd" \
         --config $PD_CONFIG &
     # wait until PD is online...
     i=0
-    while ! run_curl "https://$PD_ADDR/pd/api/v1/version"; do
+    while ! curl -o /dev/null -sf "http://$PD_ADDR/pd/api/v1/version"; do
        i=$((i+1))
        if [ "$i" -gt 20 ]; then
           echo 'Failed to start PD'
@@ -86,68 +89,21 @@ start_pd() {
        fi
        sleep 3
     done
-}
 
-kv_outage() {
-    dur=""
-    id=()
-    scale_in=false
-    scale_out=false
-    until [ $# -eq 0 ]; do
-        case $1 in
-            --duration | -d) shift; dur=$1 ;;
-            --id | -i) shift; id+=("$1") ;;
-            --scale-out) scale_out=true ;;
-            --kill) scale_in=true ;;
-        esac
-        shift
+    echo "Starting TiKV..."
+    for i in $(seq $TIKV_COUNT); do
+        mkdir -p "$TEST_DIR/tikv${i}"
+        bin/tikv-server \
+            --pd "$PD_ADDR" \
+            -A "$TIKV_ADDR$i" \
+            --status-addr "$TIKV_STATUS_ADDR$i" \
+            --log-file "$TEST_DIR/tikv${i}.log" \
+            -C "$TIKV_CONFIG" \
+            -s "$TEST_DIR/tikv${i}" &
     done
 
-    $scale_out || { 
-        for i in "${id[@]}"; do
-            target=$(cat "${TIKV_PIDS}_$i" | awk '{print $1}')
-            echo "killing TiKV $target(#$i)"
-            kill "$target" || true
-            sleep 1
-            kill -9 "$target" || true
-        done 
-    }
-    $scale_in || $scale_out || sleep "$dur"
-    $scale_in || {
-        for i in "${id[@]}"; do
-            if [ -e "${TIKV_PIDS}_$i" ]; then
-                TIKV_CONFIG=$(cat "${TIKV_PIDS}_$i" | awk '{print $2}')
-            else
-                TIKV_CONFIG=${TIKV_CONFIG:-"tests/config/tikv.toml"}
-            fi
-            start_tikv "$i"
-        done
-        # let tikv start up completely if backup is finished before tikv restarts
-        ensure_tikv
-        # sometimes even though a tikv node is stopped, pd also show is_intialized in ensure_tikv
-        sleep 1
-    }
-}
-
-start_tikv() {
-    i=$1
-    echo "Starting TiKV($i)..."
-    mkdir -p "$TEST_DIR/tikv${i}"
-    bin/tikv-server \
-        --pd "$PD_ADDR" \
-        -A "$TIKV_ADDR$i" \
-        --status-addr "$TIKV_STATUS_ADDR$i" \
-        --log-file "$TEST_DIR/tikv${i}.log" \
-        --log-level info \
-        -C "$TIKV_CONFIG" \
-        -s "$TEST_DIR/tikv${i}" &
-    pid=$!
-    echo -e "$pid\t$TIKV_CONFIG" > "${TIKV_PIDS}_${i}"
-}
-
-ensure_tikv() {
     echo "Waiting initializing TiKV..."
-    while ! run_curl "https://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
+    while ! curl -sf "http://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
        i=$((i+1))
        if [ "$i" -gt 20 ]; then
           echo 'Failed to initialize TiKV cluster'
@@ -155,14 +111,11 @@ ensure_tikv() {
        fi
        sleep 5
     done
-}
 
-start_tidb() {
     echo "Starting TiDB..."
     bin/tidb-server \
         -P 4000 \
         --status 10080 \
-        --advertise-address="127.0.0.1" \
         --store tikv \
         --path "$PD_ADDR" \
         --config "$TIDB_CONFIG" \
@@ -170,7 +123,7 @@ start_tidb() {
 
     echo "Verifying TiDB is started..."
     i=0
-    while ! run_curl "https://$TIDB_IP:10080/status"; do
+    while ! curl -o /dev/null -sf "http://$TIDB_IP:10080/status"; do
         i=$((i+1))
         if [ "$i" -gt 50 ]; then
             echo 'Failed to start TiDB'
@@ -178,64 +131,15 @@ start_tidb() {
         fi
         sleep 3
     done
-}
 
-start_importer() {
-    echo "Starting Importer..."
-    bin/tikv-importer \
-        --addr "$IMPORTER_ADDR" \
-        --import-dir "$TEST_DIR/importer" \
-        --log-file "$TEST_DIR/importer.log" \
-        --config "tests/config/importer.toml" &
-}
-
-
-start_services_impl() {
-    stop_services || true
-    cleanup_data || true
-
-    TIDB_CONFIG="tests/config/tidb.toml"
-    TIKV_CONFIG="tests/config/tikv.toml"
-    PD_CONFIG="tests/config/pd.toml"
-    RUN_TIFLASH=true
-
-    while [[ $# -gt 0 ]]
-    do
-        local key="$1"
-
-        case $key in
-            --tidb-cfg)
-            TIDB_CONFIG="$2"
-            shift # past argument
-            shift # past value
-            ;;
-            --no-tiflash)
-            RUN_TIFLASH=false
-            shift # past argument
-            ;;
-            *)    # unknown option
-            echo "Unknown args $1"
-            exit 1
-            ;;
-        esac
-    done
-
-    rm -f "${TIKV_PIDS}*"
-
-    start_pd
-    for i in $(seq $TIKV_COUNT); do
-        start_tikv "$i"
-    done
-    ensure_tikv
-    start_tidb
-    start_importer
-
-    if $RUN_TIFLASH; then
-        start_tiflash
+    if [[ ! $@ =~ "--no-tiflash" ]]; then
+        if ! start_tiflash; then
+            return 1
+        fi
     fi
 
     i=0
-    while ! run_curl "https://$PD_ADDR/pd/api/v1/cluster/status" | grep -q "\"is_initialized\": true"; do
+    while ! curl "http://$PD_ADDR/pd/api/v1/cluster/status" -sf | grep -q "\"is_initialized\": true"; do
         i=$((i+1))
         if [ "$i" -gt 20 ]; then
             echo 'Failed to bootstrap cluster'
@@ -247,11 +151,11 @@ start_services_impl() {
 
 start_tiflash() {
     echo "Starting TiFlash..."
-    tests/_utils/make_tiflash_config
-    LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file="$TEST_DIR/tiflash.toml" &
+    LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file=$TIFLASH_CONFIG &
+    echo "TiFlash started..."
 
     i=0
-    while ! run_curl https://$TIFLASH_HTTP 1>/dev/null 2>&1; do
+    while ! curl -sf http://$TIFLASH_HTTP 1>/dev/null 2>&1; do
         i=$((i+1))
         if [ "$i" -gt 20 ]; then
             echo "failed to start tiflash"
@@ -260,6 +164,96 @@ start_tiflash() {
         echo "TiFlash seems doesn't started, retrying..."
         sleep 3
     done
+}
 
-    echo "TiFlash started."
+start_services_with_tls() {
+    stop_services
+    cleanup_data
+
+    PD_CONFIG="$1/config/pd.toml"
+    TIDB_CONFIG="$1/config/tidb.toml"
+    TIKV_CONFIG="$1/config/tikv.toml"
+
+    echo $PD_CONFIG
+    echo $TIDB_CONFIG
+    echo $TIKV_CONFIG
+
+    echo "Starting PD..."
+    bin/pd-server \
+        --client-urls "https://$PD_ADDR" \
+        --log-file "$TEST_DIR/pd.log" \
+        --config "$PD_CONFIG" \
+        --data-dir "$TEST_DIR/pd" &
+    # wait until PD is online...
+    i=0
+    while ! curl --cacert $1/certificates/ca.pem \
+        --cert $1/certificates/client.pem \
+        --key $1/certificates/client-key.pem \
+        -o /dev/null -sf "https://$PD_ADDR/pd/api/v1/version"; do
+        i=$((i+1))
+        if [ "$i" -gt 20 ]; then
+            echo 'Failed to start PD'
+            exit 1
+        fi
+        sleep 3
+    done
+
+    echo "Starting TiKV..."
+    for i in $(seq $TIKV_COUNT); do
+        bin/tikv-server \
+            --pd "$PD_ADDR" \
+            -A "$TIKV_ADDR$i" \
+            --log-file "$TEST_DIR/tikv${i}.log" \
+            -C "$TIKV_CONFIG" \
+            -s "$TEST_DIR/tikv${i}" &
+    done
+
+    echo "Waiting initializing TiKV..."
+    while ! curl --cacert $1/certificates/ca.pem \
+            --cert $1/certificates/client.pem \
+            --key $1/certificates/client-key.pem \
+            -sf "https://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
+       i=$((i+1))
+       if [ "$i" -gt 20 ]; then
+          echo 'Failed to initialize TiKV cluster'
+          exit 1
+       fi
+       sleep 3
+    done
+
+    echo "Starting TiDB..."
+    bin/tidb-server \
+        -P 4000 \
+        --status 10080 \
+        --store tikv \
+        --config "$TIDB_CONFIG" \
+        --path "$PD_ADDR" \
+        --log-file "$TEST_DIR/tidb.log" &
+
+    echo "Verifying TiDB is started..."
+    i=0
+    while ! curl --cacert $1/certificates/ca.pem \
+            --cert $1/certificates/client.pem \
+            --key $1/certificates/client-key.pem \
+            -o /dev/null -sf "https://$TIDB_IP:10080/status"; do
+        i=$((i+1))
+        if [ "$i" -gt 50 ]; then
+            echo 'Failed to start TiDB'
+            exit 1
+        fi
+        sleep 3
+    done
+
+    i=0
+    while ! curl --cacert $1/certificates/ca.pem \
+            --cert $1/certificates/client.pem \
+            --key $1/certificates/client-key.pem \
+            "https://$PD_ADDR/pd/api/v1/cluster/status" -sf | grep -q "\"is_initialized\": true"; do
+        i=$((i+1))
+        if [ "$i" -gt 20 ]; then
+            echo 'Failed to bootstrap cluster'
+            exit 1
+        fi
+        sleep 3
+    done
 }
